#!/bin/bash

sudo pacman -S --needed git base-devel
git clone https://aur.archlinux.org/yay.git
cd yay
makepkg -si

yay -S --needed accountsservice acroread alsa-firmware alsa-utils apulse arc-gtk-theme arc-solid-gtk-theme archiso
yay -S --needed autoconf autocutsel automake b43-fwcutter base bash-completion betterdiscord bind
yay -S --needed binutils bison bleachbit blockify brave-bin broadcom-wl-dkms bspwm btrfs-progs cdrdao cdrtools
yay -S --needed cli-visualizer cmatrix code cozette-otb cozette-ttf cryptsetup date-git dd_rescue ddrescue
yay -S --needed device-mapper dhclient dhcpcd dialog dina-font discord dkms dmenu dnsmasq dosfstools dvdauthor e2fsprogs efibootmgr
yay -S --needed exa exfat-utils f2fs-tools faac faad2 fakeroot fbida fbpdf-git feh ffmpegthumbnailer file filezilla findutils firefox
yay -S --needed flex frei0r-plugins fuse2 fuse3 gawk gcc gdb geany gettext gimp git gnome-tweaks gparted grep
yay -S --needed groff grsync grub gst-libav gst-plugins-bad gst-plugins-base gst-plugins-good gst-plugins-ugly gst-transcoder gstreamer-vaapi
yay -S --needed gtk-engine-murrine gtk-engines guvcview gvfs gvfs-afc gvfs-goa gvfs-gphoto2 gvfs-mtp gvfs-nfs gvfs-smb
yay -S --needed gzip hardinfo haveged hdparm htop imagemagick inetutils intel-ucode inter-font ipw2100-fw ipw2200-fw iwd jfsutils less
yay -S --needed lf-git lib32-nvidia-utils libdvdcss libreoffice-fresh libtool libxft-bgra lightdm lightdm-gtk-greeter
yay -S --needed lightdm-gtk-greeter-settings lightdm-webkit-theme-litarvan lightdm-webkit2-greeter linux linux-firmware
yay -S --needed linux-lts linux-lts-headers logrotate lsb-release lsscsi lutris lvm2 lxappearance m4 make man-pages
yay -S --needed mdadm mencoder mjpegtools mkinitcpio mlocate modemmanager mpv mtools nano neofetch neovim nerd-fonts-hack net-tools
yay -S --needed netctl network-manager-applet networkmanager networkmanager-openvpn newsboat nfs-utils nilfs-utils nitrogen nomacs
yay -S --needed notification-daemon noto-fonts noto-fonts-emoji npm ntfs-3g nvidia-lts opendesktop-fonts openoffice os-prober otf-ipafont otf-san-francisco
yay -S --needed otf-takao p7zip packagekit pacman pacman-contrib paper-icon-theme-git papirus-icon-theme patch pavucontrol
yay -S --needed pcmanfm picom pkgconf pkgfile playerctl polybar posy-cursors pulseaudio pulseaudio-alsa pulseaudio-equalizer pulseaudio-jack
yay -S --needed python-pip python-pynvim qbittorrent qt5ct ranger reflector reiserfsprogs rsync rxvt-unicode s-nail samba scrot sdparm
yay -S --needed sed sg3_utils siji-git simplescreenrecorder smartmontools soundconverter sox speedtest-cli spicetify-cli spotify
yay -S --needed st sudo sxhkd sxiv sysfsutils terminus-font-otb termite testdisk texinfo thunderbird tldr tmux tor torbrowser-launcher
yay -S --needed transcode ttf-bitstream-vera ttf-courier-prime ttf-dejavu ttf-font-awesome ttf-hack ttf-iosevka ttf-liberation ttf-material-icons-git ttf-mathtype ttf-ms-fonts ttf-nerd-fonts-symbols ttf-opensans
yay -S --needed ttf-roboto ttf-ubuntu-font-family ufetch-git ufw unace unimatrix-git unrar unzip urxvt-resize-font-git usb_modeswitch
yay -S --needed usbutils vim vimix-gtk-themes-git virtualbox vsftpd wget which whois wireless_tools woeusb xbindkeys xcompmgr
yay -S --needed xdg-user-dirs xf86-input-evdev xf86-input-libinput xf86-input-synaptics xf86-input-vmmouse xf86-input-void xf86-video-amdgpu xf86-video-ati
yay -S --needed xf86-video-dummy xf86-video-fbdev xf86-video-intel xf86-video-nouveau xf86-video-openchrome xf86-video-qxl xf86-video-vesa xf86-video-vmware xf86-video-voodoo xfsprogs xorg-bdftopcf xorg-docs xorg-font-util xorg-fonts-100dpi xorg-fonts-75dpi xorg-fonts-encodings xorg-iceauth xorg-luit xorg-mkfontscale xorg-server
yay -S --needed xorg-server-common xorg-server-xephyr xorg-server-xnest xorg-server-xvfb xorg-server-xwayland xorg-sessreg xorg-setxkbmap xorg-smproxy xorg-x11perf xorg-xauth xorg-xbacklight xorg-xcmsdb xorg-xcursorgen xorg-xdpyinfo xorg-xdriinfo xorg-xev xorg-xgamma xorg-xhost xorg-xinit xorg-xinput xorg-xkbcomp xorg-xkbevd xorg-xkbutils xorg-xkill xorg-xlsatoms xorg-xlsclients xorg-xmodmap xorg-xpr xorg-xprop xorg-xrandr xorg-xrdb xorg-xrefresh xorg-xset xorg-xsetroot xorg-xvinfo xorg-xwd xorg-xwininfo xorg-xwud
yay -S --needed yarn yay youtube-dl ytop zsh
