#! /bin/sh

sxhkd &

feh --bg-fill ~/Pictures/wallpaper3.jpg &

bash $HOME/.config/polybar/launch.sh

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# window border and window gap
bspc config border_width         2
bspc config window_gap          10

# custom configuration
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true
