#! /bin/sh

sxhkd & 

feh --bg-fill ~/Downloads/autumn_trees_road_fog_landscape_4288x2848.jpg &

spotify &

#for swallowing

(ps x | grep bspswallow | grep -v grep) || bspswallow &

source $HOME/.config/polybar/launch.sh &
source $HOME/complaunch.sh &
source $HOME/zplug1.sh &
source $HOME/.scripts/spotify/launchlistener.sh &

# workspaces
bspc monitor -d 1 2 3 4 5 6 7 8 9

# window border and window gap
bspc config border_width         2
bspc config window_gap          10

# custom configuration
bspc config split_ratio 0.50
bspc config borderless_monocle false
bspc config gapless_monocle false
bspc config pointer_follows_focus true
bspc config focus_follows_pointer false
bspc config single_monocle true
